### PR TITLE
Update artifacts.ts

### PR DESCRIPTION
**Pull request by pasviegas**
Tests are failing after renaming AllowanceModule file

### CODE REVIEW

**Comment by pasviegas** [comment]
recheck

**Comment by mmv08** [comment]
Hey, thanks! Could you please sign the CLA?

**Review by mmv08 — APPROVED** [review]

**Comment by mmv08** [comment]
Ah, I saw you accepted it in a different pr

**Review by mmv08 — APPROVED** [review]

**Comment by pasviegas** [comment]
I can, thank you for being so responsive!

**Comment by pasviegas** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by pasviegas** [comment]
recheck

**Review by nlordell — APPROVED** [review]

**Comment by mmv08** [comment]
> Dang, something is up with the CLA bot...


It looks like the personal access token by the it team is missing write permissions. I have notified the IT team to check it.

**Pull request merged**
