### PR TITLE
Feature: Adjust compiler settings and document optimizer usage

### PR DESCRIPTION
**Pull request by mmv08**
This PR:
- Adjusts the compiler settings to use the latest `solc` compiler and document the settings

### CODE REVIEW

**Review by nlordell — APPROVED** [review]

**Comment by nlordell** [comment]
Out of curiosity, is the opcode `PUSH0`, and which chains don't support it still?

**Comment by mmv08** [comment]
> Out of curiosity, is the opcode `PUSH0`, and do you know off the top of your head which chains don't support it still (if not, don't worry about answering)?

Yes, it's the one. In my case, it was polygon Mumbai and a local hardhat node :D

**Comment by nlordell** [comment]
Just noticed, but the `solc` version in `package.json` is still `0.8.14`. I think this would affect the "local verify" task.

**Comment by mmv08** [comment]
> Just noticed, but the `solc` version in `package.json` is still `0.8.14`. I think this would affect the "local verify" task.

Yes, and also the code size one. I don't know if relying on a separate solc dependency is optimal instead of using the one from Hardhat. But in the meantime, it would be great if you adjust it in your testing PR, or I can create a separate PR to address this.

**Pull request merged**
