### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by pasviegas**
Change dutchx_seller module package name after converting to monorepo so it doesn't conflict with other packages in the same repo

### CODE REVIEW

**Comment by pasviegas** [comment]
recheck

**Review by mmv08 — APPROVED** [review]

**Comment by pasviegas** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by nlordell — APPROVED** [review]

**Comment by pasviegas** [comment]
recheck

**Comment by mmv08** [comment]
> recheck

Just FYI, there seems to be a problem with the access token that the action uses to store your consent. I notified the IT team to look into it

**Pull request merged**
