### PR TITLE
Certora Prover setup and properties for the audit of Passkey module

### PR DESCRIPTION
**Pull request by hristo-grigorov**
This PR includes the setup files (.conf files, harnesses, munged .sol files) and .spec files with properties for the different contracts as part of the Passkey module audit by Certora.

All the rules were verified using the latest certora-cli (7.14.2).

### CODE REVIEW

**Comment by mmv08** [comment]
Could you please move the folder from root to `modules/passkey`? Since this is a monorepo and the rules only concern the passkey, it's better placed there.

You can also enable the "allow edits from maintainers" option so we can fix small nits ourselves.

**Comment by hristo-grigorov** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by nlordell** [comment]
For the CLA - the individual commit authors need to sign it for the bot. Alternatively, you can squash the commits into one with a single author to make it easier :)

**Comment by remedcu** [comment]
Closing in favor of #496

**Pull request closed without merging**
