### PR TITLE
Setup NPM workspaces

### LINKED ISSUE #146: Set up NPM Workspace for Safe Modules
## Context / issue

Currently, all modules are currently split into separate NPM packages with their own set of dependencies. This ends up causing configuration drift between the modules (Yarn/NPM, linting, etc.) which is not idea.

## Proposed solution

In order to facilitate code sharing (such as Hardhat tasks, Safe infrastructure deployment code) and development processes (such as linting, formatting), we should convert this monorepo into an NPM workspace.

### PR DESCRIPTION
**Pull request by akshay-ap**
Fixes #146 

Summary: This PR proposes use of NPM workspaces which will work as a monorepo where the packages (Safe modules) 
 would be stored in `modules` directory. The root `package.json` of the project should store all the shared dependencies (code formatting, linting, and possibly typescript version as well).

Changes in PR:
- Remove modules:
    - dutchx_seller
    - recurring_transfers
- Move below modules to `modules/` directory which is marked as a workspaces directory in root `package.json`
    - allowances
    - 4337
    - 4337-gas-metering (though this is not another module). **Perhaps this directory should be in `packages/` directory?**

 - The root `package.json` contains dependencies related to code formatting and linting (`eslint` and `prettier`) instead of each of the package having individual configurations and dependency versions
 - Changes in `allowances` modules:
    - Uses Safe contracts `1.4.1` version
- Changes in github workflow files:
    - Update working directory
    - Update paths wherever required for the workflow to pass
    - Update npm commands in each workflow file to consider appropriate workspace
- Update README.md:
    - Remove references to dutchx_seller module
    - Update paths of existing modules

### CODE REVIEW

**Comment by mmv08** [comment]
It looks like `prettier-plugin-solidity` isn't included in the root dependency list and is nested in one of the package's dependencies. Other than that, it looks good so far.

**Review by mmv08 — APPROVED** [review]

**Review by mmv08 — CHANGES_REQUESTED** [review]
One bug I found: the `fmt` command defined globally doesn't respect the `.prettierignore` file of individual packages. I ran it, and it formatted the FCL files despite being explicitly ignored in the package.

It seems like it's a long-awaited feature: https://github.com/prettier/prettier/issues/4081

For now, I'd suggest:
1. Define the `fmt` command in each package that will take into account all the package-specific configuration
2. Keep the global command for formatting everything but packages (markdown, GitHub actions, package.json, etc.)

**Comment by akshay-ap** [comment]
> One bug I found: the `fmt` command defined globally doesn't respect the `.prettierignore` file of individual packages. I ran it, and it formatted the FCL files despite being explicitly ignored in the package.
> 
> It seems like it's a long-awaited feature: [prettier/prettier#4081](https://github.com/prettier/prettier/issues/4081)
> 
> For now, I'd suggest:
> 
> 1. Define the `fmt` command in each package that will take into account all the package-specific configuration
> 2. Keep the global command for formatting everything but packages (markdown, GitHub actions, package.json, etc.)

Here https://github.com/safe-global/safe-modules/pull/199/commits/1d03625346948e84f8c036439a05eff8f81eeb0b.
Should we also setup a github workflow that verifies files in root directory other than `packages/`?

**Comment by mmv08** [comment]
> > One bug I found: the `fmt` command defined globally doesn't respect the `.prettierignore` file of individual packages. I ran it, and it formatted the FCL files despite being explicitly ignored in the package.
> > It seems like it's a long-awaited feature: [prettier/prettier#4081](https://github.com/prettier/prettier/issues/4081)
> > For now, I'd suggest:
> > 
> > 1. Define the `fmt` command in each package that will take into account all the package-specific configuration
> > 2. Keep the global command for formatting everything but packages (markdown, GitHub actions, package.json, etc.)
> 
> Here [1d03625](https://github.com/safe-global/safe-modules/commit/1d03625346948e84f8c036439a05eff8f81eeb0b). Should we also setup a github workflow that verifies files in root directory other than `packages/`?

This doesn't check the formatting in packages (point 1 from my comment), does it?

**Comment by akshay-ap** [comment]
> > > One bug I found: the `fmt` command defined globally doesn't respect the `.prettierignore` file of individual packages. I ran it, and it formatted the FCL files despite being explicitly ignored in the package.
> > > It seems like it's a long-awaited feature: [prettier/prettier#4081](https://github.com/prettier/prettier/issues/4081)
> > > For now, I'd suggest:
> > > 
> > > 1. Define the `fmt` command in each package that will take into account all the package-specific configuration
> > > 2. Keep the global command for formatting everything but packages (markdown, GitHub actions, package.json, etc.)
> > 
> > 
> > Here [1d03625](https://github.com/safe-global/safe-modules/commit/1d03625346948e84f8c036439a05eff8f81eeb0b). Should we also setup a github workflow that verifies files in root directory other than `packages/`?
> 
> This doesn't check the formatting in packages (point 1 from my comment), does it?

When `npm ci` is executed from root of the project, `packages` directory will be ignored in this [commit](https://github.com/safe-global/safe-modules/commit/1d03625346948e84f8c036439a05eff8f81eeb0b).

Screenshot 2024-01-12 at 13 53 46

Each of the package already has its own `fmt` command so, package specific formatting can be done by specifying workspace name parameter e.g. `npm run fmt -w modules/4337`.

**Comment by mmv08** [comment]
> > > > One bug I found: the `fmt` command defined globally doesn't respect the `.prettierignore` file of individual packages. I ran it, and it formatted the FCL files despite being explicitly ignored in the package.
> > > > It seems like it's a long-awaited feature: [prettier/prettier#4081](https://github.com/prettier/prettier/issues/4081)
> > > > For now, I'd suggest:
> > > > 
> > > > 1. Define the `fmt` command in each package that will take into account all the package-specific configuration
> > > > 2. Keep the global command for formatting everything but packages (markdown, GitHub actions, package.json, etc.)
> > > 
> > > 
> > > Here [1d03625](https://github.com/safe-global/safe-modules/commit/1d03625346948e84f8c036439a05eff8f81eeb0b). Should we also setup a github workflow that verifies files in root directory other than `packages/`?
> > 
> > 
> > This doesn't check the formatting in packages (point 1 from my comment), does it?
> 
> When `npm ci` is executed from root of the project, `packages` directory will be ignored in this [commit](https://github.com/safe-global/safe-modules/commit/1d03625346948e84f8c036439a05eff8f81eeb0b).
> 
> Screenshot 2024-01-12 at 13 53 46
> Each of the package already has its own `fmt` command so, package specific formatting can be done by specifying workspace name parameter e.g. `npm run fmt -w modules/4337`.

Yes, but how would it be used? I'd expect the ci to check package specific + global formatting, so `npm run fmt:global` and `npm run fmt` for packages

Also I accidentally edited your message instead of replying, sorry 🤦

**Comment by akshay-ap** [comment]
> Yes, but how would it be used?

I suggested to have a github action for global checking [here](https://github.com/safe-global/safe-modules/pull/199#issuecomment-1888766054). What you suggested is even better. Added in this [commit](https://github.com/safe-global/safe-modules/pull/199/commits/06e1fbf794d7cb673880f50c18f936e798911f96)

**Comment by mmv08** [comment]
> > Yes, but how would it be used?
> 
> I suggested to have a github action for global checking [here](https://github.com/safe-global/safe-modules/pull/199#issuecomment-1888766054). What you suggested is even better. Added in this [commit](https://github.com/safe-global/safe-modules/pull/199/commits/06e1fbf794d7cb673880f50c18f936e798911f96)

But this executed a check only on the global level without a check on the package level, or am I missing anything? Should it be `npm run fmt:global-check && npm run fmt:check` ?

**Comment by akshay-ap** [comment]
> But this executes a check only on the global level without a check on the package level, or am I missing anything? Should it be `npm run fmt:global-check && npm run fmt:check` ?

I added `ci.yml` to contain only global checks and not package specific checks because they already setup in each package (module) specific workflow

**Comment by mmv08** [comment]
> > But this executes a check only on the global level without a check on the package level, or am I missing anything? Should it be `npm run fmt:global-check && npm run fmt:check` ?
> 
> I added `ci.yml` to contain only global checks and not package specific checks because they are already setup in each package (module) specific github workflow

Ahh, makes sense, my mad. All good then

**Review by mmv08 — APPROVED** [review]

**Comment by mmv08** [comment]
My bad, I created a bunch of conflicts here. Will resolve them

**Pull request merged**
